%% evaluate_unet.m
% M3 - Multiclass Diabetic Retinopathy Segmentation Evaluation
%
% PURPOSE:
% Evaluates the trained M3 U-Net on the complete test images
% for which all five segmentation masks are available.
%
% Classes:
%   0 = Background
%   1 = Microaneurysms
%   2 = Haemorrhages
%   3 = Hard Exudates
%   4 = Soft Exudates
%   5 = Optic Disc
%   255 = Ignore / ambiguous overlap
%
% METRICS:
%   Dice
%   IoU
%
% OUTPUT:
%   unet_test_metrics.mat
%   unet_test_metrics.csv
%   unet_test_per_image_metrics.csv
%
% -------------------------------------------------------------------------

clear;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf('       M3 MULTICLASS U-NET TEST EVALUATION\n');
fprintf('============================================================\n');

%% PROJECT PATHS

projectRoot = pwd;

modelDir = fullfile( ...
    projectRoot, ...
    'src', ...
    'segmentation', ...
    'trained_models');

outputDir = fullfile( ...
    projectRoot, ...
    'src', ...
    'segmentation', ...
    'outputs', ...
    'metrics');

%% CREATE OUTPUT DIRECTORY IF NEEDED

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% RAW IDRiD DATASET

datasetRoot = fullfile( ...
    projectRoot, ...
    '..', ...
    'A. Segmentation');

originalTestDir = fullfile( ...
    datasetRoot, ...
    '1. Original Images', ...
    'b. Testing Set');

groundTruthRoot = fullfile( ...
    datasetRoot, ...
    '2. All Segmentation Groundtruths', ...
    'b. Testing Set');

%% MODEL SELECTION

improvedBest = fullfile( ...
    modelDir, ...
    'unet_multiclass_improved_best.mat');

improvedFinal = fullfile( ...
    modelDir, ...
    'unet_multiclass_improved_final.mat');

baselineBest = fullfile( ...
    modelDir, ...
    'unet_multiclass_best.mat');

baselineFinal = fullfile( ...
    modelDir, ...
    'unet_multiclass_final.mat');

initialModel = fullfile( ...
    modelDir, ...
    'unet_multiclass_initial.mat');

%% SELECT IMPROVED MODEL FIRST

if exist(improvedBest,'file')

    modelFile = improvedBest;

elseif exist(improvedFinal,'file')

    modelFile = improvedFinal;

elseif exist(baselineBest,'file')

    modelFile = baselineBest;

elseif exist(baselineFinal,'file')

    modelFile = baselineFinal;

elseif exist(initialModel,'file')

    modelFile = initialModel;

else

    error(['No trained U-Net model was found.\n' ...
        'Expected directory:\n%s'], ...
        modelDir);

end

%% DISPLAY MODEL

fprintf('\nLoading model:\n%s\n',modelFile);

modelData = load(modelFile,'net');

net = modelData.net;

fprintf('\nModel loaded successfully.\n');

%% INPUT SIZE

inputSize = [512 512 3];

numClasses = 6;

classNames = { ...
    'Background', ...
    'MA', ...
    'HE', ...
    'Hard EX', ...
    'Soft EX', ...
    'OD'};

%% FIND TEST IMAGES

testFiles = dir(fullfile(originalTestDir,'IDRiD_*.jpg'));

totalTestImages = numel(testFiles);

fprintf('\nTotal test images found: %d\n', ...
    totalTestImages);

%% MASK DIRECTORIES

maskDirs = { ...
    fullfile(groundTruthRoot,'1. Microaneurysms'), ...
    fullfile(groundTruthRoot,'2. Haemorrhages'), ...
    fullfile(groundTruthRoot,'3. Hard Exudates'), ...
    fullfile(groundTruthRoot,'4. Soft Exudates'), ...
    fullfile(groundTruthRoot,'5. Optic Disc')};

maskSuffixes = { ...
    '_MA.tif', ...
    '_HE.tif', ...
    '_EX.tif', ...
    '_SE.tif', ...
    '_OD.tif'};

%% FIND COMPLETE TEST IMAGES

completeIDs = {};

for i = 1:numel(testFiles)

    [~,baseName,~] = fileparts(testFiles(i).name);

    isComplete = true;

    for c = 1:5

        maskFile = fullfile( ...
            maskDirs{c}, ...
            [baseName maskSuffixes{c}]);

        if ~exist(maskFile,'file')

            isComplete = false;
            break;

        end

    end

    if isComplete

        completeIDs{end+1,1} = baseName;

    end

end

numTestImages = numel(completeIDs);

fprintf( ...
    'Complete test images with all 5 masks: %d\n', ...
    numTestImages);

%% DISPLAY TEST IDS

fprintf('\nTest images that will be evaluated:\n');

for i = 1:numTestImages

    fprintf('  %s\n',completeIDs{i});

end

%% PREALLOCATE METRICS

diceScores = zeros( ...
    numTestImages, ...
    numClasses);

iouScores = zeros( ...
    numTestImages, ...
    numClasses);

%% START EVALUATION

fprintf('\n');
fprintf('============================================================\n');
fprintf('STARTING TEST EVALUATION\n');
fprintf('============================================================\n');

for imageIndex = 1:numTestImages

    imageID = completeIDs{imageIndex};

    fprintf('\n[%d/%d] Evaluating %s\n', ...
        imageIndex, ...
        numTestImages, ...
        imageID);

    %% READ ORIGINAL IMAGE

    imageFile = fullfile( ...
        originalTestDir, ...
        [imageID '.jpg']);

    originalImage = imread(imageFile);

    %% PREPARE IMAGE

    I = im2single(originalImage);

    I = imresize( ...
        I, ...
        inputSize(1:2));

    %% CREATE DLARRAY

    dlX = dlarray( ...
        reshape( ...
            I, ...
            inputSize(1), ...
            inputSize(2), ...
            3, ...
            1), ...
        'SSCB');

    %% PREDICT

    dlYPred = predict(net,dlX);

    Y = gather(extractdata(dlYPred));

    Y = squeeze(Y);

    if ndims(Y) ~= 3

        error( ...
            'Unexpected prediction dimensions for %s.', ...
            imageID);

    end

    %% NORMALIZE PROBABILITIES

    probabilitySum = sum(Y,3);

    Y = Y ./ max(probabilitySum,eps);

    %% GET PREDICTED CLASS

    [~,predictedClass] = max(Y,[],3);

    predictedMask = uint8(predictedClass - 1);

    %% READ FIVE GROUND-TRUTH MASKS

    groundTruthMasks = false( ...
        inputSize(1), ...
        inputSize(2), ...
        5);

    for c = 1:5

        maskFile = fullfile( ...
            maskDirs{c}, ...
            [imageID maskSuffixes{c}]);

        M = imread(maskFile);

        % Convert to logical binary mask

        M = M > 0;

        % Resize using nearest-neighbor

        M = imresize( ...
            M, ...
            inputSize(1:2), ...
            'nearest');

        groundTruthMasks(:,:,c) = M;

    end

    %% CREATE MULTICLASS GROUND TRUTH

    groundTruth = zeros( ...
        inputSize(1), ...
        inputSize(2), ...
        'uint8');

    overlapCount = sum( ...
        groundTruthMasks, ...
        3);

    %% OVERLAPPING ANNOTATIONS

    overlapPixels = overlapCount > 1;

    groundTruth(overlapPixels) = 255;

    %% SINGLE-CLASS PIXELS

    for c = 1:5

        uniqueClassPixels = ...
            groundTruthMasks(:,:,c) & ...
            (overlapCount == 1);

        groundTruth(uniqueClassPixels) = uint8(c);

    end

    %% BACKGROUND

    backgroundPixels = ...
        overlapCount == 0;

    groundTruth(backgroundPixels) = 0;

    %% CALCULATE DICE AND IOU

    validPixels = groundTruth ~= 255;

    for classID = 0:5

        predictionClass = ...
            predictedMask == classID;

        targetClass = ...
            groundTruth == classID;

        predictionClass = ...
            predictionClass & validPixels;

        targetClass = ...
            targetClass & validPixels;

        intersection = nnz( ...
            predictionClass & targetClass);

        predictionArea = nnz(predictionClass);

        targetArea = nnz(targetClass);

        %% DICE

        diceScores(imageIndex,classID+1) = ...
            (2 * intersection + 1) / ...
            (predictionArea + targetArea + 1);

        %% IOU

        unionArea = nnz( ...
            predictionClass | targetClass);

        iouScores(imageIndex,classID+1) = ...
            (intersection + 1) / ...
            (unionArea + 1);

    end

    %% DISPLAY IMAGE RESULTS

    fprintf( ...
        '  Dice: Background=%.4f MA=%.4f HE=%.4f Hard EX=%.4f Soft EX=%.4f OD=%.4f\n', ...
        diceScores(imageIndex,1), ...
        diceScores(imageIndex,2), ...
        diceScores(imageIndex,3), ...
        diceScores(imageIndex,4), ...
        diceScores(imageIndex,5), ...
        diceScores(imageIndex,6));

    fprintf( ...
        '  IoU : Background=%.4f MA=%.4f HE=%.4f Hard EX=%.4f Soft EX=%.4f OD=%.4f\n', ...
        iouScores(imageIndex,1), ...
        iouScores(imageIndex,2), ...
        iouScores(imageIndex,3), ...
        iouScores(imageIndex,4), ...
        iouScores(imageIndex,5), ...
        iouScores(imageIndex,6));

end

%% FINAL RESULTS

meanDice = mean( ...
    diceScores, ...
    1);

meanIoU = mean( ...
    iouScores, ...
    1);

%% MEAN FOREGROUND METRICS

meanForegroundDice = mean( ...
    meanDice(2:6));

meanForegroundIoU = mean( ...
    meanIoU(2:6));

%% DISPLAY FINAL RESULTS

fprintf('\n');
fprintf('============================================================\n');
fprintf('FINAL TEST RESULTS\n');
fprintf('============================================================\n');

fprintf('\n');

fprintf( ...
    '%-15s %-12s %-12s\n', ...
    'Class', ...
    'Dice', ...
    'IoU');

fprintf( ...
    '------------------------------------------------------------\n');

for c = 1:numClasses

    fprintf( ...
        '%-15s %-12.4f %-12.4f\n', ...
        classNames{c}, ...
        meanDice(c), ...
        meanIoU(c));

end

fprintf( ...
    '------------------------------------------------------------\n');

fprintf( ...
    '%-15s %-12.4f %-12.4f\n', ...
    'Mean Foreground', ...
    meanForegroundDice, ...
    meanForegroundIoU);

fprintf( ...
    '============================================================\n');

%% SAVE MAT FILE

metricsFile = fullfile( ...
    outputDir, ...
    'unet_test_metrics.mat');

save( ...
    metricsFile, ...
    'meanDice', ...
    'meanIoU', ...
    'meanForegroundDice', ...
    'meanForegroundIoU', ...
    'diceScores', ...
    'iouScores', ...
    'completeIDs', ...
    'classNames', ...
    'modelFile');

fprintf('\nMetrics saved to:\n%s\n', ...
    metricsFile);

%% SAVE AGGREGATE CSV

aggregateTable = table( ...
    classNames(:), ...
    meanDice(:), ...
    meanIoU(:), ...
    'VariableNames', ...
    {'Class','Dice','IoU'});

aggregateCsv = fullfile( ...
    outputDir, ...
    'unet_test_metrics.csv');

writetable( ...
    aggregateTable, ...
    aggregateCsv);

fprintf('\nCSV metrics saved to:\n%s\n', ...
    aggregateCsv);

%% SAVE PER-IMAGE CSV

perImageTable = table( ...
    completeIDs, ...
    diceScores(:,1), ...
    diceScores(:,2), ...
    diceScores(:,3), ...
    diceScores(:,4), ...
    diceScores(:,5), ...
    diceScores(:,6), ...
    iouScores(:,1), ...
    iouScores(:,2), ...
    iouScores(:,3), ...
    iouScores(:,4), ...
    iouScores(:,5), ...
    iouScores(:,6), ...
    'VariableNames', ...
    { ...
    'ImageID', ...
    'Dice_Background', ...
    'Dice_MA', ...
    'Dice_HE', ...
    'Dice_HardEX', ...
    'Dice_SoftEX', ...
    'Dice_OD', ...
    'IoU_Background', ...
    'IoU_MA', ...
    'IoU_HE', ...
    'IoU_HardEX', ...
    'IoU_SoftEX', ...
    'IoU_OD'});

perImageCsv = fullfile( ...
    outputDir, ...
    'unet_test_per_image_metrics.csv');

writetable( ...
    perImageTable, ...
    perImageCsv);

fprintf('\nPer-image metrics saved to:\n%s\n', ...
    perImageCsv);

%% FINAL SUMMARY

fprintf('\n');
fprintf('============================================================\n');
fprintf('M3 EVALUATION COMPLETED SUCCESSFULLY\n');
fprintf('============================================================\n');

fprintf('Model evaluated:\n%s\n',modelFile);

fprintf('\nNumber of evaluated test images: %d\n', ...
    numTestImages);

fprintf('\nMean Foreground Dice = %.4f\n', ...
    meanForegroundDice);

fprintf('Mean Foreground IoU  = %.4f\n', ...
    meanForegroundIoU);

fprintf('\nM3 evaluation step complete.\n');