function mapping = getClinicalMappings(grade)
% GETCLINICALMAPPINGS Medical mapping adhering to International Clinical Diabetic Retinopathy (ICDR) Scale
%
% Syntax:
%   mapping = getClinicalMappings()          % Returns all 5 clinical levels
%   mapping = getClinicalMappings(grade)     % Returns specific mapping for grade 0-4
%
% Inputs:
%   grade - (Optional) Integer scalar from 0 to 4
%
% Outputs:
%   mapping - Struct containing clinical definitions, referable status,
%             urgency levels, and recommended follow-up timelines.
%
% Reference:
%   Wilkinson CP et al., Proposed international clinical diabetic retinopathy
%   and diabetic macular edema disease severity scales. Ophthalmology, 2003.
%
% Authors: SIH 2026 Team (Member 4 - Explainable AI: labdhimehta-2311)

    persistent clinicalDB
    if isempty(clinicalDB)
        clinicalDB = containers.Map('KeyType', 'int32', 'ValueType', 'any');
        
        clinicalDB(0) = struct(...
            'grade', 0, ...
            'name', 'No Apparent Retinopathy', ...
            'shortName', 'No DR', ...
            'clinicalFeatures', 'No microaneurysms, hemorrhages, or exudates detectable.', ...
            'referableDR', false, ...
            'urgency', 'ROUTINE', ...
            'recommendation', 'Routine annual retinal screening; maintain tight glycemic and BP control.', ...
            'followUpTimeline', '12 months');
            
        clinicalDB(1) = struct(...
            'grade', 1, ...
            'name', 'Mild Non-Proliferative Diabetic Retinopathy', ...
            'shortName', 'Mild NPDR', ...
            'clinicalFeatures', 'Microaneurysms only. No other retinal lesions present.', ...
            'referableDR', false, ...
            'urgency', 'MONITOR', ...
            'recommendation', 'Repeat screening in 6 to 12 months; review diabetes care with primary physician.', ...
            'followUpTimeline', '6-12 months');
            
        clinicalDB(2) = struct(...
            'grade', 2, ...
            'name', 'Moderate Non-Proliferative Diabetic Retinopathy', ...
            'shortName', 'Moderate NPDR', ...
            'clinicalFeatures', 'More than microaneurysms but less than Severe NPDR (scattered hemorrhages, exudates, cotton-wool spots).', ...
            'referableDR', true, ...
            'urgency', 'REFERRAL', ...
            'recommendation', 'Refer to ophthalmologist for comprehensive dilated retinal examination within 4 to 6 weeks.', ...
            'followUpTimeline', '4-6 weeks');
            
        clinicalDB(3) = struct(...
            'grade', 3, ...
            'name', 'Severe Non-Proliferative Diabetic Retinopathy', ...
            'shortName', 'Severe NPDR', ...
            'clinicalFeatures', 'Meets ICDR 4-2-1 rule: >20 hemorrhages in 4 quadrants, venous beading in 2+ quadrants, or IRMA in 1+ quadrant.', ...
            'referableDR', true, ...
            'urgency', 'HIGH_PRIORITY_REFERRAL', ...
            'recommendation', 'High-priority referral to vitreoretinal specialist within 2 to 4 weeks. High risk of progression to PDR.', ...
            'followUpTimeline', '2-4 weeks');
            
        clinicalDB(4) = struct(...
            'grade', 4, ...
            'name', 'Proliferative Diabetic Retinopathy', ...
            'shortName', 'Proliferative DR (PDR)', ...
            'clinicalFeatures', 'Neovascularization of the disc (NVD) or retina (NVE), preretinal/vitreous hemorrhage, or fibrovascular proliferation.', ...
            'referableDR', true, ...
            'urgency', 'URGENT', ...
            'recommendation', 'URGENT vitreoretinal referral within 1 to 2 weeks for consideration of panretinal photocoagulation or anti-VEGF therapy.', ...
            'followUpTimeline', '1-2 weeks');
    end

    if nargin < 1 || isempty(grade)
        % Return all mappings as a struct array
        mapping = [clinicalDB(0), clinicalDB(1), clinicalDB(2), clinicalDB(3), clinicalDB(4)];
    else
        gradeInt = int32(grade);
        if ~isKey(clinicalDB, gradeInt)
            error('Invalid DR Grade: %d. Grade must be an integer between 0 and 4.', grade);
        end
        mapping = clinicalDB(gradeInt);
    end
end
